icon_paths: "icons/"
zoom: {'sun': 0.1, 'earth': 0.01}
id: {'sun': 0, 'mercury': 1, 'venus': 2, 'earth': 3, 'true_earth': 399, 'moon': 301, 'mars': 4, 'jupyter': 5, 'saturn': 6, 'uranus': 7, 'neptune': 8, 'pluto': 9}